### ISSUE TITLE
Reflection Padding

### ISSUE THREAD

**Issue by alokwhitewolf** [naoto0804/chainer-cyclegan#1]
First, I would like to appreciate your effort. You are probably the only one I found who has implemented Instance Normalization.

In Johnson's paper, the input is padded with via reflection padding in the residual blocks. Is there any way to implement the same in chainer ?

**Comment by alokwhitewolf** [comment]
Edit:- I meant in the original cycle GAN paper

**Comment by naoto0804** [comment]
Thank you for visiting this repository!!
You can use `chainer.functions.pad` by specifying `keywords` option
http://docs.chainer.org/en/stable/reference/generated/chainer.functions.pad.html

By the way,
if you are using PyTorch, there is an official implementation of Instance Normalization.  (https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/instancenorm.py)
You can also find implementations in TF (https://github.com/lengstrom/fast-style-transfer/blob/1424228ea48cb8a65f50d0490900f29b92f1dc4f/src/transform.py)

**Comment by naoto0804** [comment]
@alokwhitewolf Thank you for visiting this repository!!
You can use `chainer.functions.pad` by specifying `mode` option
http://docs.chainer.org/en/stable/reference/generated/chainer.functions.pad.html
(For the keywords you can use, please refer to  https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html,
because Chainer actually uses the numpy's implementation.)

By the way,
if you are using PyTorch, there is an official implementation of Instance Normalization.  (https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/instancenorm.py)
You can also find implementations in TF (https://github.com/lengstrom/fast-style-transfer/blob/1424228ea48cb8a65f50d0490900f29b92f1dc4f/src/transform.py)
